dictionaries = ["en_us"]
words = [
    "eslint",
    "idxs",
    "jsdom",
    "mts",
    "networkidle",
    "oxc",
    "oxlint",
    "readwrite",
    "ssr",
    "trunc",
    "tx",
    "upgradeneeded",
    "vite",
    "vitejs",
    "vitest",
]
ignore_paths = [
    ".git/**/*",
    "dist/**/*",
    "node_modules/**/*",
]
