dictionaries = ["en_us"]
words = [
	"eslint",
	"idxs",
	"jsdom",
	"mts",
	"oxc",
	"oxlint",
	"oxlint",
	"readwrite",
	"ssr",
	"tx",
	"upgradeneeded",
	"vite",
	"vitest",
	"vitejs",
	"trunc",
]
flag_words = []
ignore_paths = [".git/**/*", "dist/**/*", "node_modules/**/*"]
ignore_patterns = []
