name = "sudoku"
main = "./.output/server/index.mjs"
compatibility_date = "2025-07-30"
compatibility_flags = ["nodejs_compat"]

[vars]
DEPLOYMENT_ID = "fake-local-id"
DEPLOYMENT_TIMESTAMP = "2025-08-06T00:00:00Z"
DEPLOY_URL = "http://127.0.0.1:8787"
PULL_REQUEST_URL = "http://localhost:3000/fake-pr"

[assets]
binding = "ASSETS"
directory = "./.output/public"

[observability]
enabled = true

# --- Production Environment ---

[env.production]
name = "sudoku-production"
main = "./.output/server/index.mjs"
compatibility_flags = ["nodejs_compat"]

[env.production.assets]
binding = "ASSETS"
directory = "./.output/public"

[env.production.vars]
DEPLOYMENT_ID = "production"
DEPLOYMENT_TIMESTAMP = ""
DEPLOY_URL = ""
PULL_REQUEST_URL = ""

# --- Staging Environment ---

[env.staging]
name = "sudoku-staging"
main = "./.output/server/index.mjs"
compatibility_flags = ["nodejs_compat"]

[env.staging.assets]
binding = "ASSETS"
directory = "./.output/public"

[env.staging.vars]
DEPLOYMENT_ID = "staging"
DEPLOYMENT_TIMESTAMP = ""
DEPLOY_URL = ""
PULL_REQUEST_URL = ""
