name = "sudoku"
main = "./.output/server/index.mjs"
compatibility_date = "2025-07-31"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./.output/public"

[observability]
enabled = true

[vars]
DEPLOYMENT_ID = "production"
DEPLOY_URL = ""

[env.staging]
name = "sudoku"
[env.staging.vars]
DEPLOYMENT_ID = "staging"
DEPLOY_URL = ""
