name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CACHE_KEY_PREFIX: deps-v1
  NODE_VERSION_FILE: ".nvmrc"

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package-lock.json') }}
          path: |
            node_modules

  browsers:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: "npm"

      - name: Restore node modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package-lock.json') }}
          path: |
            node_modules

      - name: Install Playwright browsers
        run: npm run install-browsers -- --with-deps

      - name: Cache browsers
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-browsers-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package.json') }}
          path: |
            ~/.cache/ms-playwright

  check:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: "npm"

      - name: Restore node modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package-lock.json') }}
          path: |
            node_modules

      - name: Check format
        run: npm run check:format

      # - name: Check types
      #   run: npm run check:types

      # - name: Lint check
      #   run: npm run check:lint

  test:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: "npm"

      - name: Restore node modules cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package-lock.json') }}
          path: |
            node_modules

      - name: Run unit tests
        run: npm run test:unit

  build:
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: "npm"

      - name: Restore cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package-lock.json') }}
          path: |
            node_modules

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: output
          path: .svelte-kit/output
          if-no-files-found: error
          retention-days: 14

  e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          cache: "npm"

      - name: Restore node modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package-lock.json') }}
          path: |
            node_modules

      - name: Restore browsers
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-browsers-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package.json') }}
          path: |
            ~/.cache/ms-playwright

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: output
          path: .svelte-kit/output

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
