name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CACHE_KEY_PREFIX: deps-v1
  BUN_VERSION_FILE: '.bun-version'
  PLAYWRIGHT_CACHE_PATH: '~/.cache/ms-playwright'

jobs:
  install-browsers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          key: ${{ runner.os }}-browsers-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('bun.lock') }}
          path: ${{ env.PLAYWRIGHT_CACHE_PATH }}

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: bun run install-browsers -- --with-deps

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check format
        run: bun run check:format

      - name: Check types
        run: bun run check:types

      # - name: Lint check
      #   run: bun run check:lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run unit tests
        run: bun run test:unit

  build:
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: output
          path: .svelte-kit/output
          if-no-files-found: error
          retention-days: 14

  e2e:
    needs: [install-browsers, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Restore browsers
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-browsers-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('bun.lock') }}
          path: ${{ env.PLAYWRIGHT_CACHE_PATH }}

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: output
          path: .svelte-kit/output

      - name: Run E2E tests
        run: bun run test:e2e

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
