name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CACHE_KEY_PREFIX: deps-v1

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v20

      - name: Install npm dependencies
        run: nix develop --command npm ci

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package-lock.json') }}
          path: |
            node_modules

  check:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v20

      - name: Restore node modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package-lock.json') }}
          path: |
            node_modules

      - name: Check format
        run: nix develop --command npm run check:format

      # - name: Check types
      #   run: nix develop --command npm run check:types

      # - name: Lint check
      #   run: nix develop --command npm run check:lint

  test:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v20

      - name: Restore node modules cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package-lock.json') }}
          path: |
            node_modules

      - name: Install browsers for tests
        run: npx playwright install --with-deps chromium

      - name: Run unit tests
        run: nix develop --command npm run test:unit

  build:
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v20

      - name: Restore cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package-lock.json') }}
          path: |
            node_modules

      - name: Build
        run: nix develop --command npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: output
          path: .svelte-kit/output
          if-no-files-found: error
          retention-days: 14

  performance:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v20

      - name: Restore node modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package-lock.json') }}
          path: |
            node_modules

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: output
          path: .svelte-kit/output

      - name: Run Lighthouse CI
        run: nix develop --command npm run lighthouse

  e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v20

      - name: Restore cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('package-lock.json') }}
          path: |
            node_modules

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: output
          path: .svelte-kit/output

      - name: Install browsers for E2E tests
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: nix develop --command npm run test:e2e

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
