name: CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  # this stem might be removed when all jobs will move to bun,
  # as it's faster to install deps than pulling them from cache
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment

  install-browsers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      - uses: ./.github/actions/browsers

  quality-checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        check: [check:format, check:types, check:lint, check:typegen]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      - name: Check ${{ matrix.check }}
        run: bun run ${{ matrix.check }}

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/browsers
      - uses: ./.github/actions/setup-environment

      - name: Run unit tests
        run: npm run test:unit:run

  test-browser:
    needs: [install-dependencies, install-browsers, test-unit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/browsers
      - uses: ./.github/actions/setup-environment
        with:
          # override runtime due to vitest being incompatible with bun
          runtime: node

      - name: Run unit tests in browser
        run: npm run test:browser:run

  build:
    needs: [quality-checks, test-browser]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      - uses: ./.github/actions/build-artifacts
        with:
          operation: upload

  e2e:
    needs: [install-browsers, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      - uses: ./.github/actions/browsers
      - uses: ./.github/actions/build-artifacts
        with:
          operation: download
      - name: Run E2E tests
        run: DEBUG=pw:webserver bun run test:e2e
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    needs: [build, e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      - uses: ./.github/actions/build-artifacts
        with:
          operation: download
      - uses: ./.github/actions/deploy
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workers-subdomain: ${{ secrets.CLOUDFLARE_WORKER_SUBDOMAIN }}
          project-name: ${{ secrets.CLOUDFLARE_APP_WORKER_NAME }}
