name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  CACHE_KEY_PREFIX: deps-v1
  BUN_VERSION_FILE: ".bun-version"
  NODE_VERSION_FILE: ".node-version"
  PLAYWRIGHT_CACHE_PATH: "~/.cache/ms-playwright"
  BUILD_ARTIFACTS_NAME: "build-output"
  BUILD_ARTIFACTS_DIR_NAME: ".output"
  BUILD_ARTIFACTS: |
    .output/public/**
    .output/server/**
    .output/_headers
    .output/nitro.json
    .output/package.json
    .output/package-lock.json

jobs:
  # this stem might be removed when all jobs will move to bun,
  # as it's faster to install deps than pulling them from cache
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-environment

  install-browsers:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-environment
      - uses: ./.github/actions/browsers

  quality-checks:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        check: [format, types, lint]
    steps:
      - uses: ./.github/actions/setup-environment
      - name: Check ${{ matrix.check }}
        run: bun run check:${{ matrix.check }}

  test:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-environment
        with:
          # override runtime due to vitest being incompatible with bun
          runtime: node

      - name: Run unit tests
        run: npm run test:unit

  build:
    needs: [install-dependencies, check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-environment
      - uses: ./.github/actions/build-artifacts
        with:
          operation: upload

  e2e:
    needs: [install-dependencies, install-browsers, build]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-environment
      - uses: ./.github/actions/browsers
      - uses: ./.github/actions/build-artifacts
        with:
          operation: download
      - name: Run E2E tests
        run: DEBUG=pw:webserver bun run test:e2e
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    needs: [build, e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-environment
      - uses: ./.github/actions/build-artifacts
        with:
          operation: download
      - uses: ./.github/actions/deploy
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workers-subdomain: ${{ secrets.WORKERS_SUBDOMAIN }}
