name: Deploy Staging (Manual)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: main

env:
  BUILD_ARTIFACTS_NAME: "build-output"
  BUILD_ARTIFACTS_DIR_NAME: ".output"
  BUN_VERSION_FILE: ".bun-version"

jobs:
  deploy-preprod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-modules-${{ hashFiles('bun.lock') }}
          path: node_modules

      - name: Download artifact from latest CI run
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          branch: ${{ github.event.inputs.branch }}
          name: ${{ env.BUILD_ARTIFACTS_NAME }}
          path: ${{ env.BUILD_ARTIFACTS_DIR_NAME }}

      - name: Deploy to Staging
        run: bun wrangler deploy --env staging
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
