## 4. Deploy Preview (for PRs)
# preview:
#   if: github.event_name == 'pull_request'
#   needs: build
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v4
#     - name: Download build
#       uses: actions/download-artifact@v4
#       with:
#         name: build
#         path: build/
#     - name: Deploy to Netlify
#       uses: nwtgck/actions-netlify@v2
#       with:
#         publish-dir: "./build"
#         production-deploy: false
#         github-token: ${{ secrets.GITHUB_TOKEN }}
#         deploy-message: "Deploy Preview for PR #${{ github.event.number }}"
#       env:
#         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

# deploy:
#   if: github.ref == 'refs/heads/main'
#   needs: [build, e2e]
#   runs-on: ubuntu-latest
#   steps:
#     - name: Download build
#       uses: actions/download-artifact@v4
#       with:
#         name: build
#         path: build/
#     - name: Deploy to production
#       uses: cloudflare/wrangler-action@v3
#       with:
#         apiToken: ${{ secrets.CF_API_TOKEN }}
#         accountId: ${{ secrets.CF_ACCOUNT_ID }}
#         command: pages deploy build/
