name: Deploy Staging Run

on:
  repository_dispatch:
    types: [deploy-staging]

env:
  BUILD_ARTIFACTS_NAME: "build-output"
  BUILD_ARTIFACTS_DIR_NAME: ".output"
  BUN_VERSION_FILE: ".bun-version"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Comment: deployment started"
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.client_payload.pull_request.number }}
          body: |
            🚧 Starting staging deployment for PR #${{ github.event.client_payload.pull_request.number }}...

      - name: Download artifact from latest CI run
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          pr: ${{ github.event.client_payload.pull_request.number }}
          name: ${{ env.BUILD_ARTIFACTS_NAME }}
          path: ${{ env.BUILD_ARTIFACTS_DIR_NAME }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-modules-${{ hashFiles('bun.lock') }}
          path: node_modules

      - name: Generate Deployment ID
        run: echo "DEPLOYMENT_ID=pr-${{ github.event.client_payload.pull_request.number }}-$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Deploy to Staging
        run: bun wrangler deploy --name sudoku-pr-${{ github.event.client_payload.pull_request.number }} --var DEPLOYMENT_ID:${{ env.DEPLOYMENT_ID }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: "Comment: deployment finished"
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.client_payload.pull_request.number }}
          body: |
            🚀 Deployed to staging!

            **URL:** https://sudoku-pr-${{ github.event.client_payload.pull_request.number }}.lizon-patryk.workers.dev
            **Deployment ID:** `${{ env.DEPLOYMENT_ID }}`
