name: Deploy Staging (Triggered)

on:
  repository_dispatch:
    types: [deploy-staging]

env:
  BUILD_ARTIFACTS_NAME: "build-output"
  BUILD_ARTIFACTS_DIR_NAME: ".output"
  BUN_VERSION_FILE: ".bun-version"
  PR_NUMBER: ${{ github.event.number }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from latest CI run
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          pr: ${{ github.event.client_payload.pull_request.number }}
          name: ${{ env.BUILD_ARTIFACTS_NAME }}
          path: ${{ env.BUILD_ARTIFACTS_DIR_NAME }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ${{ env.BUN_VERSION_FILE }}

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node-modules-${{ hashFiles('bun.lock') }}
          path: node_modules

      - name: Deploy to Staging
        run: bun wrangler deploy --name ${{ env.PR_NUMBER }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
