name: Deploy Staging via PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  dispatch:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/deploy-staging') }}
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Deploy Workflow
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reactions: true
          issue-type: pull-request
          permission: write
          commands: |
            deploy-staging
